### ISSUE TITLE
REQUEST: Multiarch support

### ISSUE THREAD

**Issue by theniwo** [fradelg/docker-mysql-cron-backup#38] opened 2021-02-20 06:21 UTC
Hi, could there be multiarch support for arm cpus?

**Comment by fradelg** [comment] 2021-03-06 12:32
Hi, 

Can you try to pull the latest tag and check if it works?

https://hub.docker.com/layers/fradelg/mysql-cron-backup/latest/images/sha256-aa297609ff1faa2b50b39afed3116e523fb18a9a5cf2990498c3a39b2fae9a33?context=explore

**Comment by theniwo** [comment] 2021-03-06 14:39
I get 
`/usr/local/bin/dockerize: line 1: syntax error: unexpected word (expecting ")")`
using yobasystems/alpine-mariadb

**Comment by fradelg** [comment] 2021-03-06 18:42
It seems like dockerize does not support arm in Alpine:

https://github.com/jwilder/dockerize/issues/154

**Comment by theniwo** [comment] 2021-03-06 19:10
I can try using 
jc21/mariadb-aria:10.4

**Comment by fradelg** [comment] 2021-03-07 10:39
The problem is with this docker image for backup, not with the database server.

I have tried to recompile dockerize instead of downloading the official release from the author. Can you try again with the tag `buildx`:

fradelg/mysql-cron-backup:buildx

**Comment by theniwo** [comment] 2021-03-07 11:20
Ok, it starts and does a backup, but 
```
docker container exec nginx-proxy-manager_db_backup_1 /restore.sh /backup/latest.npm.sql.gz
=> Restore database from /backup/latest.npm.sql.gz
ERROR 1046 (3D000) at line 22: No database selected
=> Restore failed
```

**Comment by fradelg** [comment] 2021-03-07 11:57
Some users complained about including the USE statement in the backup so you have to create and use the database before restoring.

I have added a new argument to the mysql restore command to use the database in MYSQL_DATABASE but the database still have to be created before running the restore.sh script

You can use use the MariaDB container to restore a previous backup as the README explains:

```
- ${VOLUME_PATH}/backup/latest.${DATABASE_NAME}.sql.gz:/docker-entrypoint-initdb.d/database.sql.gz
```

**Comment by fradelg** [comment] 2021-03-13 11:42
Hi, can I close the issue and release a new version?

**Comment by theniwo** [comment] 2021-03-13 11:57
Hi,
Yes, it works now. Thank you

**Closed** 2021-03-15 20:30 UTC
